var product = {
	"sellPrice" : 1,
	"createTime" : "2017-06-25 11:24:58",
	"spu" : "1",
	"deletedStatus" : 1,
	"visibility" : 1,
	"updateTime" : "2017-06-25 11:24:56",
	"status" : 1,
	"manageStock" : 1,
	"metaKeywords" : "1",
	"metaDescription" : "1",
	"storeDefault" : 1,
	"metaTitle" : "1",
	"type" : 1,
	"isBackorder" : 1,
	"isBundle" : 1,
	"id" : 1,
	"groupSellId" : 1,
	"originalPrice" : 1,
	"description" : "",
	"name" : "测试",
	"storeId" : 1,
	"design" : "1"
};