dubbo :
  protocol : 
    prot : -1
    name  : dubbo
  application : 
    name : vankle-dubbo-app
  registry :
    address : zookeeper://127.0.0.1:2181
  packageName : com.vankle.catalog.service.impl
  
server :
  port : 8083  
spring: 
  profiles:  
    active: dev  
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  