dubbo :
  protocol : 
    prot : -1
    name  : dubbo
    port : 20889
  application : 
    name : vankle-dubbo-app
  registry :
    address : zookeeper://localhost:2181
  packageName : com.vankle.catalog.service.impl
  
server :
  port : 8086  
spring: 
  profiles:  
    active: dev  
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  