var result = {
	"code" : "10000",
	"msg" : "成功",
	"data" : {
		"groupSellId" : 4,
		"isBundle" : 0,
		"manageStock" : 0,
		"storeDefault" : 1,
		"originalPrice" : 359,
		"visibility" : 1,
		"description" : "",
		"sellPrice" : 359,
		"updateTime" : "2017-07-25 13:50:12",
		"storeId" : 1,
		"type" : 2,
		"metaDescription" : "",
		"isBackorder" : 0,
		"metaKeywords" : "",
		"createTime" : "2017-07-21 13:36:00",
		"design" : "",
		"metaTitle" : "",
		"name" : "Miniature Bridge Series Tiara Shaped Designer Promise Ring ",
		"spu" : "NRC0478",
		"id" : 367,
		"deletedStatus" : 1,
		"status" : 1,
		"catalogProductEntityDiscount" : {
			"discountPercentage" : 0.42,
			"productId" : 367,
			"createTime" : "",
			"discountEndTime" : "2017-07-21 13:36:00",
			"discountStartTime" : "2017-07-21 13:36:00",
			"discountAmount" : 149,
			"updateTime" : "",
			"id" : 366,
			"storeId" : 1,
			"deletedStatus" : 0
		},
		"catalogProductGroupSell" : {
			"createTime" : null,
			"name" : "group111",
			"description" : "test",
			"updateTime" : null,
			"id" : 4,
			"storeId" : 0,
			"deletedStatus" : 0,
			"list" : [{
				"groupSellId" : 0,
				"isBundle" : 0,
				"manageStock" : 0,
				"storeDefault" : 1,
				"originalPrice" : 399,
				"visibility" : 1,
				"description" : "",
				"sellPrice" : 399,
				"updateTime" : "2017-07-24 09:15:39",
				"storeId" : 1,
				"type" : 1,
				"metaDescription" : "",
				"isBackorder" : 0,
				"metaKeywords" : "",
				"createTime" : "2017-07-21 13:36:20",
				"design" : "",
				"metaTitle" : "",
				"name" : "Love Bridge Inspired Cityscape Ruby Promise Ring With Heart Lock By Designer",
				"spu" : "NRC0479",
				"id" : 368,
				"deletedStatus" : 1,
				"status" : 1,
				"catalogProductEntityDiscount" : {
					"discountPercentage" : 0.45,
					"productId" : 368,
					"createTime" : "",
					"discountEndTime" : "2017-07-21 13:36:20",
					"discountStartTime" : "2017-07-21 13:36:20",
					"discountAmount" : 179,
					"updateTime" : "",
					"id" : 367,
					"storeId" : 1,
					"deletedStatus" : 0
				},
				"catalogProductSpecList" : [{
							"productId" : 368,
							"description" : "",
							"updateTime" : null,
							"sort" : 0,
							"storeId" : 1,
							"type" : 2,
							"createTime" : null,
							"name" : "color",
							"id" : 79,
							"value" : "1",
							"deletedStatus" : 0,
							"status" : 1,
							"catalogProductSpecValueList" : [{
										"createTime" : null,
										"productSpecId" : 79,
										"name" : "red",
										"updateTime" : null,
										"id" : 83,
										"value" : "1",
										"deletedStatus" : 0,
										"status" : 1
									}, {
										"createTime" : null,
										"productSpecId" : 79,
										"name" : "golden",
										"updateTime" : null,
										"id" : 84,
										"value" : "3",
										"deletedStatus" : 0,
										"status" : 1
									}]
						}, {
							"productId" : 368,
							"description" : "",
							"updateTime" : null,
							"sort" : 0,
							"storeId" : 1,
							"type" : 2,
							"createTime" : null,
							"name" : "size",
							"id" : 80,
							"value" : "2",
							"deletedStatus" : 0,
							"status" : 1,
							"catalogProductSpecValueList" : [{
										"createTime" : null,
										"productSpecId" : 80,
										"name" : "6(U.S.)\\16.45(mm)",
										"updateTime" : null,
										"id" : 85,
										"value" : "1",
										"deletedStatus" : 0,
										"status" : 1
									}, {
										"createTime" : null,
										"productSpecId" : 80,
										"name" : "6.5(U.S.)\\16.9(mm)",
										"updateTime" : null,
										"id" : 86,
										"value" : "2",
										"deletedStatus" : 0,
										"status" : 1
									}, {
										"createTime" : null,
										"productSpecId" : 80,
										"name" : "7(U.S.)\\17.3(mm)",
										"updateTime" : null,
										"id" : 87,
										"value" : "3",
										"deletedStatus" : 0,
										"status" : 1
									}]
						}],
				"catalogProductEntityImages" : [{
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
					"productId" : 368,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
					"updateTime" : null,
					"id" : 2173,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-5-0706.jpg",
					"productId" : 368,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-5-0706.jpg",
					"updateTime" : null,
					"id" : 2174,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-4-0706.jpg",
					"productId" : 368,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-4-0706.jpg",
					"updateTime" : null,
					"id" : 2175,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-3-0706.jpg",
					"productId" : 368,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-3-0706.jpg",
					"updateTime" : null,
					"id" : 2176,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-2-0706.jpg",
					"productId" : 368,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-2-0706.jpg",
					"updateTime" : null,
					"id" : 2177,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0708_1.jpg",
					"productId" : 368,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0708_1.jpg",
					"updateTime" : null,
					"id" : 2178,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/x/i/xinbaozhuang001_3_162.jpg",
					"productId" : 368,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/x/i/xinbaozhuang001_3_162.jpg",
					"updateTime" : null,
					"id" : 2179,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}],
				"catalogProductEntityVideos" : []
			}, {
				"groupSellId" : 0,
				"isBundle" : 0,
				"manageStock" : 0,
				"storeDefault" : 1,
				"originalPrice" : 249,
				"visibility" : 1,
				"description" : "<p style=\"text-align: left;\"><strong>High Quality Cubic Zirconia Rings from VANCARO<\/strong><\/p>\n\n<p>Do you want to know what exactly makes VANCARO so superior to other cubic zirconia jewelry? There may be three points: 1. Purity of rough material.  2. Cutting technique.  3. Polishing technique. We only use the world&rsquo;s finest, highly trained professionals hand-cut stones. With our unique and thorough polishing technique, our stones have the shimmering, sparkling beauty,which makes it looks as brilliant or as real looking as priceless diamonds.<\/p>\n\n<iframe class=\"dec_video\" src=\"http://www.youtube.com/embed/zXjl5PBFL94?rel=0\" frameborder=\"0\" allowfullscreen><\/iframe> ",
				"sellPrice" : 249,
				"updateTime" : "",
				"storeId" : 1,
				"type" : 1,
				"metaDescription" : "",
				"isBackorder" : 1,
				"metaKeywords" : "",
				"createTime" : "2017-07-20 16:04:08",
				"design" : "",
				"metaTitle" : "",
				"name" : "1.9 CT Cushion Cut Women's Engagement Ring 925 Sterling Silver Platinum Plated CZ Ring",
				"spu" : "VRRW0038",
				"id" : 11,
				"deletedStatus" : 1,
				"status" : 1,
				"catalogProductEntityDiscount" : {
					"discountPercentage" : 0.52,
					"productId" : 11,
					"createTime" : "",
					"discountEndTime" : "2017-07-20 16:04:08",
					"discountStartTime" : "2017-07-20 16:04:08",
					"discountAmount" : 129,
					"updateTime" : "",
					"id" : 10,
					"storeId" : 1,
					"deletedStatus" : 0
				},
				"catalogProductSpecList" : [{
							"productId" : 11,
							"description" : "",
							"updateTime" : null,
							"sort" : 0,
							"storeId" : 1,
							"type" : 2,
							"createTime" : null,
							"name" : "color",
							"id" : 70,
							"value" : "1",
							"deletedStatus" : 0,
							"status" : 1,
							"catalogProductSpecValueList" : []
						}, {
							"productId" : 11,
							"description" : "",
							"updateTime" : null,
							"sort" : 0,
							"storeId" : 1,
							"type" : 2,
							"createTime" : null,
							"name" : "size",
							"id" : 71,
							"value" : "2",
							"deletedStatus" : 0,
							"status" : 1,
							"catalogProductSpecValueList" : []
						}],
				"catalogProductEntityImages" : [{
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/_/-/_-1_5.jpg",
					"productId" : 11,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/_/-/_-1_5.jpg",
					"updateTime" : null,
					"id" : 1,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/t/b/tb2kccbrvxxxxc1xxxxxxxxxxxx__2844235177_.jpg",
					"productId" : 11,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/t/b/tb2kccbrvxxxxc1xxxxxxxxxxxx__2844235177_.jpg",
					"updateTime" : null,
					"id" : 2,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw0038newimage1004.jpg",
					"productId" : 11,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw0038newimage1004.jpg",
					"updateTime" : null,
					"id" : 3,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw0038newimage1003.jpg",
					"productId" : 11,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw0038newimage1003.jpg",
					"updateTime" : null,
					"id" : 4,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw0038newimage1002.jpg",
					"productId" : 11,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw0038newimage1002.jpg",
					"updateTime" : null,
					"id" : 5,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw0038newimage1001.jpg",
					"productId" : 11,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw0038newimage1001.jpg",
					"updateTime" : null,
					"id" : 6,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw0038newimage1005.jpg",
					"productId" : 11,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw0038newimage1005.jpg",
					"updateTime" : null,
					"id" : 7,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/s/s/ss098-2.jpg",
					"productId" : 11,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/s/s/ss098-2.jpg",
					"updateTime" : null,
					"id" : 8,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw00380329.jpg",
					"productId" : 11,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw00380329.jpg",
					"updateTime" : null,
					"id" : 9,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/s/s/ss098-10.jpg",
					"productId" : 11,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/s/s/ss098-10.jpg",
					"updateTime" : null,
					"id" : 10,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw00380423-1.jpg",
					"productId" : 11,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/v/r/vrrw00380423-1.jpg",
					"updateTime" : null,
					"id" : 11,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}, {
					"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/x/i/xinbaozhuang001_3_83.jpg",
					"productId" : 11,
					"productSpecValueId" : 0,
					"createTime" : null,
					"resType" : 1,
					"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/x/i/xinbaozhuang001_3_83.jpg",
					"updateTime" : null,
					"id" : 12,
					"url" : "",
					"deletedStatus" : 0,
					"status" : 0
				}],
				"catalogProductEntityVideos" : []
			}]
		},
		"catalogProductSpecList" : [],
		"catalogProductEntityImages" : [{
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0478-2-0706.jpg",
			"productId" : 367,
			"productSpecValueId" : 0,
			"createTime" : null,
			"resType" : 1,
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0478-2-0706.jpg",
			"updateTime" : null,
			"id" : 2167,
			"url" : "",
			"deletedStatus" : 0,
			"status" : 0
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0478-4-0706.jpg",
			"productId" : 367,
			"productSpecValueId" : 0,
			"createTime" : null,
			"resType" : 1,
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0478-4-0706.jpg",
			"updateTime" : null,
			"id" : 2168,
			"url" : "",
			"deletedStatus" : 0,
			"status" : 0
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0478-5-0706.jpg",
			"productId" : 367,
			"productSpecValueId" : 0,
			"createTime" : null,
			"resType" : 1,
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0478-5-0706.jpg",
			"updateTime" : null,
			"id" : 2169,
			"url" : "",
			"deletedStatus" : 0,
			"status" : 0
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0478-1-0706.jpg",
			"productId" : 367,
			"productSpecValueId" : 0,
			"createTime" : null,
			"resType" : 1,
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0478-1-0706.jpg",
			"updateTime" : null,
			"id" : 2170,
			"url" : "",
			"deletedStatus" : 0,
			"status" : 0
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0478-3-0706.jpg",
			"productId" : 367,
			"productSpecValueId" : 0,
			"createTime" : null,
			"resType" : 1,
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0478-3-0706.jpg",
			"updateTime" : null,
			"id" : 2171,
			"url" : "",
			"deletedStatus" : 0,
			"status" : 0
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/x/i/xinbaozhuang001_3_161.jpg",
			"productId" : 367,
			"productSpecValueId" : 0,
			"createTime" : null,
			"resType" : 1,
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/x/i/xinbaozhuang001_3_161.jpg",
			"updateTime" : null,
			"id" : 2172,
			"url" : "",
			"deletedStatus" : 0,
			"status" : 0
		}],
		"catalogProductEntityVideos" : []
	}
}
