var result = {
	"code" : "10000",
	"msg" : "成功",
	"data" : {
		"groupSellId" : 0,
		"isBundle" : 0,
		"manageStock" : 0,
		"storeDefault" : 1,
		"originalPrice" : 399,
		"visibility" : 1,
		"description" : "",
		"sellPrice" : 399,
		"updateTime" : "2017-07-24 09:15:39",
		"storeId" : 1,
		"type" : 1,
		"metaDescription" : "",
		"isBackorder" : 0,
		"metaKeywords" : "",
		"createTime" : "2017-07-21 13:36:20",
		"design" : "",
		"metaTitle" : "",
		"name" : "Love Bridge Inspired Cityscape Ruby Promise Ring With Heart Lock By Designer",
		"spu" : "NRC0479",
		"id" : 368,
		"deletedStatus" : 1,
		"status" : 1,
		"catalogProductEntityDiscount" : {
			"discountPercentage" : 0.45,
			"productId" : 368,
			"createTime" : "",
			"discountEndTime" : "2017-07-21 13:36:20",
			"discountStartTime" : "2017-07-21 13:36:20",
			"discountAmount" : 179,
			"updateTime" : "",
			"id" : 367,
			"storeId" : 1,
			"deletedStatus" : 0
		},
		"catalogProductSpecList" : [{
					"productId" : 368,
					"description" : "",
					"updateTime" : null,
					"sort" : 0,
					"storeId" : 1,
					"type" : 2,
					"createTime" : null,
					"name" : "color",
					"id" : 79,
					"value" : "1",
					"deletedStatus" : 0,
					"status" : 1,
					"catalogProductSpecValueList" : [{
								"createTime" : null,
								"productSpecId" : 79,
								"name" : "red",
								"updateTime" : null,
								"id" : 83,
								"value" : "1",
								"deletedStatus" : 0,
								"status" : 1
							}, {
								"createTime" : null,
								"productSpecId" : 79,
								"name" : "golden",
								"updateTime" : null,
								"id" : 84,
								"value" : "3",
								"deletedStatus" : 0,
								"status" : 1
							}]
				}, {
					"productId" : 368,
					"description" : "",
					"updateTime" : null,
					"sort" : 0,
					"storeId" : 1,
					"type" : 2,
					"createTime" : null,
					"name" : "size",
					"id" : 80,
					"value" : "2",
					"deletedStatus" : 0,
					"status" : 1,
					"catalogProductSpecValueList" : [{
								"createTime" : null,
								"productSpecId" : 80,
								"name" : "6(U.S.)\\16.45(mm)",
								"updateTime" : null,
								"id" : 85,
								"value" : "1",
								"deletedStatus" : 0,
								"status" : 1
							}, {
								"createTime" : null,
								"productSpecId" : 80,
								"name" : "6.5(U.S.)\\16.9(mm)",
								"updateTime" : null,
								"id" : 86,
								"value" : "2",
								"deletedStatus" : 0,
								"status" : 1
							}, {
								"createTime" : null,
								"productSpecId" : 80,
								"name" : "7(U.S.)\\17.3(mm)",
								"updateTime" : null,
								"id" : 87,
								"value" : "3",
								"deletedStatus" : 0,
								"status" : 1
							}]
				}],
		"catalogProductEntityImages" : [{
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
			"productId" : 368,
			"productSpecValueId" : 0,
			"createTime" : null,
			"resType" : 1,
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
			"updateTime" : null,
			"id" : 2173,
			"url" : "",
			"deletedStatus" : 0,
			"status" : 0
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-5-0706.jpg",
			"productId" : 368,
			"productSpecValueId" : 0,
			"createTime" : null,
			"resType" : 1,
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-5-0706.jpg",
			"updateTime" : null,
			"id" : 2174,
			"url" : "",
			"deletedStatus" : 0,
			"status" : 0
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-4-0706.jpg",
			"productId" : 368,
			"productSpecValueId" : 0,
			"createTime" : null,
			"resType" : 1,
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-4-0706.jpg",
			"updateTime" : null,
			"id" : 2175,
			"url" : "",
			"deletedStatus" : 0,
			"status" : 0
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-3-0706.jpg",
			"productId" : 368,
			"productSpecValueId" : 0,
			"createTime" : null,
			"resType" : 1,
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-3-0706.jpg",
			"updateTime" : null,
			"id" : 2176,
			"url" : "",
			"deletedStatus" : 0,
			"status" : 0
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-2-0706.jpg",
			"productId" : 368,
			"productSpecValueId" : 0,
			"createTime" : null,
			"resType" : 1,
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-2-0706.jpg",
			"updateTime" : null,
			"id" : 2177,
			"url" : "",
			"deletedStatus" : 0,
			"status" : 0
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0708_1.jpg",
			"productId" : 368,
			"productSpecValueId" : 0,
			"createTime" : null,
			"resType" : 1,
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0708_1.jpg",
			"updateTime" : null,
			"id" : 2178,
			"url" : "",
			"deletedStatus" : 0,
			"status" : 0
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/x/i/xinbaozhuang001_3_162.jpg",
			"productId" : 368,
			"productSpecValueId" : 0,
			"createTime" : null,
			"resType" : 1,
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/x/i/xinbaozhuang001_3_162.jpg",
			"updateTime" : null,
			"id" : 2179,
			"url" : "",
			"deletedStatus" : 0,
			"status" : 0
		}],
		"catalogProductEntityVideos" : [{
			"productId" : 368,
			"resType" : 1,
			"updateTime" : null,
			"url" : "",
			"productSpecValueId" : 1,
			"createTime" : null,
			"imageUrl" : "http://www.vancaro.com/media/catalog/product/cache/1/thumbnail/171x99/9df78eab33525d08d6e5fb8d27136e95/1/l/1lmrTNg9sOs.jpg",
			"name" : "High Quality Cubic Zirconia Rings from VANCARO",
			"remoteUrl" : "www.youtube.com/embed/1lmrTNg9sOs",
			"id" : 1,
			"deletedStatus" : 0,
			"status" : 1
		}],
		"catalogProductRecommendeds" : [{
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
			"productId" : 368,
			"createTime" : "2017-07-26 11:27:52",
			"updateTime" : "2017-07-26 11:27:49",
			"id" : 12,
			"position" : 1,
			"deletedStatus" : 1,
			"recommendedProductId" : 20
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
			"productId" : 368,
			"createTime" : "2017-07-26 11:27:52",
			"updateTime" : "2017-07-26 11:27:49",
			"id" : 11,
			"position" : 1,
			"deletedStatus" : 1,
			"recommendedProductId" : 19
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
			"productId" : 368,
			"createTime" : "2017-07-26 11:27:52",
			"updateTime" : "2017-07-26 11:27:49",
			"id" : 10,
			"position" : 1,
			"deletedStatus" : 1,
			"recommendedProductId" : 18
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
			"productId" : 368,
			"createTime" : "2017-07-26 11:27:52",
			"updateTime" : "2017-07-26 11:27:49",
			"id" : 9,
			"position" : 1,
			"deletedStatus" : 1,
			"recommendedProductId" : 17
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
			"productId" : 368,
			"createTime" : "2017-07-26 11:27:52",
			"updateTime" : "2017-07-26 11:27:49",
			"id" : 8,
			"position" : 1,
			"deletedStatus" : 1,
			"recommendedProductId" : 16
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
			"productId" : 368,
			"createTime" : "2017-07-26 11:27:52",
			"updateTime" : "2017-07-26 11:27:49",
			"id" : 7,
			"position" : 1,
			"deletedStatus" : 1,
			"recommendedProductId" : 15
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
			"productId" : 368,
			"createTime" : "2017-07-26 11:27:52",
			"updateTime" : "2017-07-26 11:27:49",
			"id" : 6,
			"position" : 1,
			"deletedStatus" : 1,
			"recommendedProductId" : 14
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
			"productId" : 368,
			"createTime" : "2017-07-26 11:27:52",
			"updateTime" : "2017-07-26 11:27:49",
			"id" : 5,
			"position" : 1,
			"deletedStatus" : 1,
			"recommendedProductId" : 13
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
			"productId" : 368,
			"createTime" : "2017-07-26 11:27:52",
			"updateTime" : "2017-07-26 11:27:49",
			"id" : 4,
			"position" : 1,
			"deletedStatus" : 1,
			"recommendedProductId" : 12
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
			"productId" : 368,
			"createTime" : "2017-07-26 11:27:52",
			"updateTime" : "2017-07-26 11:27:49",
			"id" : 3,
			"position" : 1,
			"deletedStatus" : 1,
			"recommendedProductId" : 11
		}, {
			"smallImage" : "https://vancaro-review-image-video.s3.amazonaws.com/product/image/n/r/nrc0479-1-0706.jpg",
			"productId" : 368,
			"createTime" : "2017-07-26 11:27:52",
			"updateTime" : "2017-07-26 11:27:49",
			"id" : 1,
			"position" : 11,
			"deletedStatus" : 1,
			"recommendedProductId" : 11
		}]
	}
}
