var dd = {
	"code" : "10000",
	"msg" : "成功",
	"data" : {
		"dataList" : [{
			"productId" : 333,
			"discountAmount" : 79,
			"sellPrice" : 189,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 0,
			"discountPercentage" : 42,
			"createTime" : "2017-09-18 11:46:31",
			"name" : "Angel Wing And Cross Earrings With Sterling Silver Stud For Women",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/s/e/sev007-1-0613.jpg",
			"id" : 3702,
			"categoryId" : 300,
			"deletedStatus" : 0
		}, {
			"productId" : 329,
			"discountAmount" : 99,
			"sellPrice" : 199,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 0,
			"discountPercentage" : 50,
			"createTime" : "2017-09-18 11:45:25",
			"name" : "Geometric Shaped White Gold Plated Honeycomb Series Woman Earrings ",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/s/e/sev006-1-0613.jpg",
			"id" : 3654,
			"categoryId" : 300,
			"deletedStatus" : 0
		}, {
			"productId" : 328,
			"discountAmount" : 79,
			"sellPrice" : 159,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 0,
			"discountPercentage" : 50,
			"createTime" : "2017-09-18 11:44:38",
			"name" : "Flower And Skeleton Classic Silver Earrings For Female",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/s/e/sev005-3-0613.jpg",
			"id" : 3646,
			"categoryId" : 300,
			"deletedStatus" : 0
		}, {
			"productId" : 327,
			"discountAmount" : 89,
			"sellPrice" : 149,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 0,
			"discountPercentage" : 60,
			"createTime" : "2017-09-18 11:43:48",
			"name" : "Gothic Style Rose And Skull Two-tone Ear Stud ",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/s/e/sev004-3-0613.jpg",
			"id" : 3638,
			"categoryId" : 300,
			"deletedStatus" : 0
		}, {
			"productId" : 325,
			"discountAmount" : 119,
			"sellPrice" : 259,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 0,
			"discountPercentage" : 46,
			"createTime" : "2017-09-18 11:42:06",
			"name" : "Daisy Series Fashion Flower Woman Earrings With Cubic Zirconias",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/s/e/sev003-01.jpg",
			"id" : 3619,
			"categoryId" : 300,
			"deletedStatus" : 0
		}, {
			"productId" : 290,
			"discountAmount" : 49,
			"sellPrice" : 109,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 0,
			"discountPercentage" : 45,
			"createTime" : "2017-09-18 10:39:33",
			"name" : "Elegant Swan Inspired Pearl Drop Earrings For Women",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/s/e/sev001-1-0419.jpg",
			"id" : 3209,
			"categoryId" : 300,
			"deletedStatus" : 0
		}, {
			"productId" : 254,
			"discountAmount" : 39,
			"sellPrice" : 59,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 1,
			"discountPercentage" : 66,
			"createTime" : "2017-09-18 09:51:41",
			"name" : "Exquisite Happy Smile Face Stud Earrings Good Luck For 2017",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/s/s/ssj04662016121701.jpg",
			"id" : 2701,
			"categoryId" : 300,
			"deletedStatus" : 0
		}, {
			"productId" : 248,
			"discountAmount" : 59,
			"sellPrice" : 99,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 1,
			"discountPercentage" : 60,
			"createTime" : "2017-09-18 09:47:06",
			"name" : "Angel Wing Heart Ear Stud In White Gold Plated Sterling Silver",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/s/s/ssj04592016112201_1.jpg",
			"id" : 2625,
			"categoryId" : 300,
			"deletedStatus" : 0
		}, {
			"productId" : 197,
			"discountAmount" : 49,
			"sellPrice" : 109,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 1,
			"discountPercentage" : 45,
			"createTime" : "2017-09-17 18:52:20",
			"name" : "Tassels Earrings for Women in Bat and Crescent Design With Pearl",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/n/r/nrc0426newimage01-0.jpg",
			"id" : 1910,
			"categoryId" : 300,
			"deletedStatus" : 0
		}, {
			"productId" : 191,
			"discountAmount" : 99,
			"sellPrice" : 239,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 1,
			"discountPercentage" : 41,
			"createTime" : "2017-09-17 18:42:31",
			"name" : "925 Sterling Silver With Pearl Meteor Series Ear Stud for Women",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/n/r/nrn0016newimage0910-0.jpg",
			"id" : 1814,
			"categoryId" : 300,
			"deletedStatus" : 0
		}, {
			"productId" : 190,
			"discountAmount" : 99,
			"sellPrice" : 225,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 1,
			"discountPercentage" : 44,
			"createTime" : "2017-09-17 18:42:07",
			"name" : "Angel Wing Earrings Asymmetry Copper Plated Black",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/n/r/nrc041320161119-00.jpg",
			"id" : 1805,
			"categoryId" : 300,
			"deletedStatus" : 0
		}, {
			"productId" : 176,
			"discountAmount" : 35,
			"sellPrice" : 35,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 1,
			"discountPercentage" : 100,
			"createTime" : "2017-09-17 17:32:33",
			"name" : "925 Sterling Silver Eiffel Tower with Cubic Zirconia Women's Ear Studs",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/l/i/likai201605100015.jpg",
			"id" : 1635,
			"categoryId" : 300,
			"deletedStatus" : 0
		}, {
			"productId" : 175,
			"discountAmount" : 35,
			"sellPrice" : 35,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 1,
			"discountPercentage" : 100,
			"createTime" : "2017-09-17 17:32:07",
			"name" : "Heart Shape with Round Cut Cubic Zirconia Women's Ear Studs",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/l/i/likai20160510007.jpg",
			"id" : 1630,
			"categoryId" : 300,
			"deletedStatus" : 0
		}, {
			"productId" : 37,
			"discountAmount" : 19.99,
			"sellPrice" : 59,
			"updateTime" : "",
			"storeId" : 1,
			"isBackorder" : 1,
			"discountPercentage" : 34,
			"createTime" : "2017-09-16 16:21:22",
			"name" : "Red Heart Crystal 925 Sterling Silver With White Gold Plated Women's Stud Earrings",
			"remoteUrl" : "https://vancaro-review-image-video.s3.amazonaws.com/product/smallimage/x/x/xxx_1.jpg",
			"id" : 346,
			"categoryId" : 300,
			"deletedStatus" : 0
		}],
		"prePageIndex" : 1,
		"curPageIndex" : 1,
		"nextPageIndex" : 1,
		"pageSize" : 30,
		"rowsCount" : 14,
		"pageCount" : 1,
		"sortBar" : [{
					"key" : "Name",
					"value" : "Name"
				}, {}, {}],
		"currency" : {
			"createTime" : null,
			"name" : "US dollar",
			"sign" : "$",
			"updateTime" : null,
			"id" : 1,
			"iso3Code" : "USD",
			"value" : "",
			"deletedStatus" : 0,
			"status" : 0
		}
	}
}
