var result = {
	"code" : "10000",
	"msg" : "成功",
	"data" : {
		"groupSellId" : 0,
		"isBundle" : 0,
		"manageStock" : 0,
		"storeDefault" : 0,
		"originalPrice" : 129,
		"description" : "<style>.short-description-list li {\r\n    list-style: none;\r\n    margin: 0;\r\n    padding: 0;\r\n}\r\n.short-description-list {\r\n    list-style: none;\r\n    margin: 0;\r\n    padding: 0;\r\n}<\/style>\r\n<p>\r\n    <strong>OVERVIEW<\/strong>\r\n<\/p>\r\n<ul class=\"short-description-list\">\r\n    <li>\r\n        <span class=\"short-name\">Gender<\/span><span class=\"short-value\">Women<\/span>\r\n    <\/li>\r\n    <li>\r\n        <span class=\"short-name\">Gemstone Size<\/span><span class=\"short-value\">6.5mm*7.5mm<\/span>\r\n    <\/li>\r\n    <li>\r\n        <span class=\"short-name\">Gemstone Setting<\/span><span class=\"short-value\">4-prong<\/span>\r\n    <\/li>\r\n    <li>\r\n        <span class=\"short-name\">Gemstone Color<\/span><span class=\"short-value\">H<\/span>\r\n    <\/li>\r\n    <li>\r\n        <span class=\"short-name\">Gemstone Cut<\/span><span class=\"short-value\">3EX<\/span>\r\n    <\/li>\r\n    <li>\r\n        <span class=\"short-name\">Approximate Carat Weight<\/span><span class=\"short-value\">VVS1<\/span>\r\n    <\/li>\r\n    <li>\r\n        <span class=\"short-name\">Jewelry Plating<\/span><span class=\"short-value\">Platinum Plated<\/span>\r\n    <\/li>\r\n    <li>\r\n        <span class=\"short-name\">Metal<\/span><span class=\"short-value\">925 Sterling Silver<\/span>\r\n    <\/li>\r\n    <li>\r\n        <span class=\"short-name\">Jewelry Finish<\/span><span class=\"short-value\">Polished<\/span> &nbsp; &nbsp; &nbsp; &nbsp;\r\n    <\/li>\r\n<\/ul>\r\n<p> Picture is for reference only, please prevail in kind.<\/p>\r\n<p>\r\n    <strong>A Short Video About How Vancaro Jewelry is Made With Our Craftman&#39;s Passion and Love<\/strong>\r\n<\/p>\r\n<div class=\"youbube_wrapper\">\r\n    <div class=\"youtube_container\">\r\n        <iframe class=\"youtube_video\" src=\"https://player.vimeo.com/video/238530230?rel=0\" frameborder=\"0\" allowfullscreen=\"\"><\/iframe>\r\n    <\/div>\r\n<\/div>\r\n    <span class=\"short-value\"><strong>DESCRIPTION<\/strong><\/span>\r\n<\/p>\r\n<p>\r\n    Love is an eternal topic in our life, because of eternity, so become classics. Therefore, the more classic of a ring symbolized love, the more popular. Looking back, with the development of the times, wedding rings are also undergoing tremendous change, but the loyalty to love should not be changed forever. This ring combines the past and the present style, the middle of a princess cut top finest cubic zircon shining eternal light.\r\n<\/p>",
		"sellPrice" : 129,
		"type" : 1,
		"metaDescription" : "",
		"isBackorder" : 0,
		"isBackorderDesc" : "",
		"metaKeywords" : "",
		"design" : "",
		"id" : 10231,
		"deletedStatus" : 1,
		"thumbnail" : "",
		"visibility" : 1,
		"updateTime" : "2017-12-08 03:04:09",
		"storeId" : 1,
		"itemId" : 10231,
		"createTime" : "2017-11-04 00:04:08",
		"metaTitle" : "",
		"name" : "1.9 CT Cushion Cut Women's Engagement Ring 925 Sterling Silver Platinum Plated CZ Ring",
		"spu" : "VRRW0038",
		"shortName" : "",
		"status" : 1,
		"currency" : {
			"createTime" : null,
			"name" : "US dollar",
			"sign" : "$",
			"updateTime" : null,
			"id" : 1,
			"iso3Code" : "USD",
			"value" : "",
			"deletedStatus" : 0,
			"status" : 0
		},
		"category" : "",
		"catalogProductEntityDiscount" : {
			"discountPercentage" : 1,
			"productId" : 231,
			"createTime" : "",
			"discountEndTime" : "2017-11-04 00:04:08",
			"discountStartTime" : "2017-11-04 00:04:08",
			"discountAmount" : 129,
			"updateTime" : "",
			"id" : 231,
			"storeId" : 1,
			"deletedStatus" : 0
		},
		"catalogProductSpecList" : [{
					"productId" : 231,
					"description" : "",
					"updateTime" : null,
					"sort" : 0,
					"storeId" : 1,
					"type" : 2,
					"createTime" : null,
					"name" : "size",
					"id" : 205,
					"value" : "1",
					"deletedStatus" : 0,
					"status" : 1,
					"catalogProductSpecValueList" : [{
								"createTime" : null,
								"productSpecId" : 205,
								"name" : "5(U.S.)\\15.6(mm)",
								"updateTime" : null,
								"id" : 1176,
								"value" : "2",
								"deletedStatus" : 0,
								"status" : 1,
								"description" : "1天"
							}, {
								"createTime" : null,
								"productSpecId" : 205,
								"name" : "6(U.S.)\\16.45(mm)",
								"updateTime" : null,
								"id" : 1177,
								"value" : "4",
								"deletedStatus" : 0,
								"status" : 1,
								"description" : "5天"
							}, {
								"createTime" : null,
								"productSpecId" : 205,
								"name" : "7(U.S.)\\17.3(mm)",
								"updateTime" : null,
								"id" : 1178,
								"value" : "6",
								"deletedStatus" : 0,
								"status" : 1,
								"description" : "3天"
							}, {
								"createTime" : null,
								"productSpecId" : 205,
								"name" : "8(U.S.)\\18.2(mm)",
								"updateTime" : null,
								"id" : 1179,
								"value" : "8",
								"deletedStatus" : 0,
								"status" : 1,
								"description" : "10天"
							}, {
								"createTime" : null,
								"productSpecId" : 205,
								"name" : "9(U.S.)\\19(mm)",
								"updateTime" : null,
								"id" : 1180,
								"value" : "10",
								"deletedStatus" : 0,
								"status" : 2,
								"description" : ""
							}, {
								"createTime" : null,
								"productSpecId" : 205,
								"name" : "10(U.S.)\\19.9(mm)",
								"updateTime" : null,
								"id" : 1181,
								"value" : "12",
								"deletedStatus" : 0,
								"status" : 1,
								"description" : ""
							}]
				}],
		"catalogProductSkuList" : [{
					"productId" : 231,
					"stockMinQty" : 0,
					"priceDifference" : 0,
					"stockQty" : 0,
					"description" : "1天",
					"updateTime" : null,
					"skuName" : "5(U.S.)\\15.6(mm)",
					"createTime" : null,
					"skuKey" : {
						"size" : "5(U.S.)\\15.6(mm)"
					},
					"id" : 1181,
					"position" : 0,
					"sku" : "VRRW0038-2",
					"deletedStatus" : 0,
					"status" : 1
				}, {
					"productId" : 231,
					"stockMinQty" : 0,
					"priceDifference" : 0,
					"stockQty" : 0,
					"description" : "5天",
					"updateTime" : null,
					"skuName" : "6(U.S.)\\16.45(mm)",
					"createTime" : null,
					"skuKey" : {
						"size" : "6(U.S.)\\16.45(mm)"
					},
					"id" : 1182,
					"position" : 1,
					"sku" : "VRRW0038-4",
					"deletedStatus" : 0,
					"status" : 1
				}, {
					"productId" : 231,
					"stockMinQty" : 0,
					"priceDifference" : 0,
					"stockQty" : 0,
					"description" : "3天",
					"updateTime" : null,
					"skuName" : "7(U.S.)\\17.3(mm)",
					"createTime" : null,
					"skuKey" : {
						"size" : "7(U.S.)\\17.3(mm)"
					},
					"id" : 1183,
					"position" : 2,
					"sku" : "VRRW0038-6",
					"deletedStatus" : 0,
					"status" : 1
				}, {
					"productId" : 231,
					"stockMinQty" : 0,
					"priceDifference" : 0,
					"stockQty" : 0,
					"description" : "10天",
					"updateTime" : null,
					"skuName" : "8(U.S.)\\18.2(mm)",
					"createTime" : null,
					"skuKey" : {
						"size" : "8(U.S.)\\18.2(mm)"
					},
					"id" : 1184,
					"position" : 3,
					"sku" : "VRRW0038-8",
					"deletedStatus" : 0,
					"status" : 1
				}, {
					"productId" : 231,
					"stockMinQty" : 0,
					"priceDifference" : 0,
					"stockQty" : 0,
					"description" : "",
					"updateTime" : null,
					"skuName" : "9(U.S.)\\19(mm)",
					"createTime" : null,
					"skuKey" : {
						"size" : "9(U.S.)\\19(mm)"
					},
					"id" : 1185,
					"position" : 4,
					"sku" : "VRRW0038-10",
					"deletedStatus" : 0,
					"status" : 2
				}, {
					"productId" : 231,
					"stockMinQty" : 0,
					"priceDifference" : 0,
					"stockQty" : 0,
					"description" : "",
					"updateTime" : null,
					"skuName" : "10(U.S.)\\19.9(mm)",
					"createTime" : null,
					"skuKey" : {
						"size" : "10(U.S.)\\19.9(mm)"
					},
					"id" : 1186,
					"position" : 5,
					"sku" : "VRRW0038-12",
					"deletedStatus" : 0,
					"status" : 1
				}],
		"catalogProductEntityImages" : [{
			"image" : "https://dftv6xrgdspaa.cloudfront.net/product/image/_/-/_-1_5.jpg",
			"thumbnail" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/_/-/_-1_5.jpg",
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/_/-/_-1_5.jpg",
			"productId" : 231,
			"resType" : 1,
			"updateTime" : null,
			"url" : "",
			"productSpecValueId" : 0,
			"createTime" : null,
			"remoteUrl" : "https://dftv6xrgdspaa.cloudfront.net/product/image/_/-/_-1_5.jpg",
			"id" : 1596,
			"position" : 0,
			"deletedStatus" : 0,
			"status" : 1
		}, {
			"image" : "https://dftv6xrgdspaa.cloudfront.net/product/image/t/b/tb2kccbrvxxxxc1xxxxxxxxxxxx__2844235177_.jpg",
			"thumbnail" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/t/b/tb2kccbrvxxxxc1xxxxxxxxxxxx__2844235177_.jpg",
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/t/b/tb2kccbrvxxxxc1xxxxxxxxxxxx__2844235177_.jpg",
			"productId" : 231,
			"resType" : 1,
			"updateTime" : null,
			"url" : "",
			"productSpecValueId" : 0,
			"createTime" : null,
			"remoteUrl" : "https://dftv6xrgdspaa.cloudfront.net/product/image/t/b/tb2kccbrvxxxxc1xxxxxxxxxxxx__2844235177_.jpg",
			"id" : 1597,
			"position" : 1,
			"deletedStatus" : 0,
			"status" : 1
		}, {
			"image" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw0038newimage1004.jpg",
			"thumbnail" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw0038newimage1004.jpg",
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw0038newimage1004.jpg",
			"productId" : 231,
			"resType" : 1,
			"updateTime" : null,
			"url" : "",
			"productSpecValueId" : 0,
			"createTime" : null,
			"remoteUrl" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw0038newimage1004.jpg",
			"id" : 1598,
			"position" : 2,
			"deletedStatus" : 0,
			"status" : 1
		}, {
			"image" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw0038newimage1003.jpg",
			"thumbnail" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw0038newimage1003.jpg",
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw0038newimage1003.jpg",
			"productId" : 231,
			"resType" : 1,
			"updateTime" : null,
			"url" : "",
			"productSpecValueId" : 0,
			"createTime" : null,
			"remoteUrl" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw0038newimage1003.jpg",
			"id" : 1599,
			"position" : 3,
			"deletedStatus" : 0,
			"status" : 1
		}, {
			"image" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw0038newimage1002.jpg",
			"thumbnail" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw0038newimage1002.jpg",
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw0038newimage1002.jpg",
			"productId" : 231,
			"resType" : 1,
			"updateTime" : null,
			"url" : "",
			"productSpecValueId" : 0,
			"createTime" : null,
			"remoteUrl" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw0038newimage1002.jpg",
			"id" : 1600,
			"position" : 4,
			"deletedStatus" : 0,
			"status" : 1
		}, {
			"image" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw0038newimage1001.jpg",
			"thumbnail" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw0038newimage1001.jpg",
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw0038newimage1001.jpg",
			"productId" : 231,
			"resType" : 1,
			"updateTime" : null,
			"url" : "",
			"productSpecValueId" : 0,
			"createTime" : null,
			"remoteUrl" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw0038newimage1001.jpg",
			"id" : 1601,
			"position" : 5,
			"deletedStatus" : 0,
			"status" : 1
		}, {
			"image" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw0038newimage1005.jpg",
			"thumbnail" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw0038newimage1005.jpg",
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw0038newimage1005.jpg",
			"productId" : 231,
			"resType" : 1,
			"updateTime" : null,
			"url" : "",
			"productSpecValueId" : 0,
			"createTime" : null,
			"remoteUrl" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw0038newimage1005.jpg",
			"id" : 1602,
			"position" : 6,
			"deletedStatus" : 0,
			"status" : 1
		}, {
			"image" : "https://dftv6xrgdspaa.cloudfront.net/product/image/s/s/ss098-2.jpg",
			"thumbnail" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/s/s/ss098-2.jpg",
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/s/s/ss098-2.jpg",
			"productId" : 231,
			"resType" : 1,
			"updateTime" : null,
			"url" : "",
			"productSpecValueId" : 0,
			"createTime" : null,
			"remoteUrl" : "https://dftv6xrgdspaa.cloudfront.net/product/image/s/s/ss098-2.jpg",
			"id" : 1603,
			"position" : 7,
			"deletedStatus" : 0,
			"status" : 1
		}, {
			"image" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw00380329.jpg",
			"thumbnail" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw00380329.jpg",
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw00380329.jpg",
			"productId" : 231,
			"resType" : 1,
			"updateTime" : null,
			"url" : "",
			"productSpecValueId" : 0,
			"createTime" : null,
			"remoteUrl" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw00380329.jpg",
			"id" : 1604,
			"position" : 8,
			"deletedStatus" : 0,
			"status" : 1
		}, {
			"image" : "https://dftv6xrgdspaa.cloudfront.net/product/image/s/s/ss098-10.jpg",
			"thumbnail" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/s/s/ss098-10.jpg",
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/s/s/ss098-10.jpg",
			"productId" : 231,
			"resType" : 1,
			"updateTime" : null,
			"url" : "",
			"productSpecValueId" : 0,
			"createTime" : null,
			"remoteUrl" : "https://dftv6xrgdspaa.cloudfront.net/product/image/s/s/ss098-10.jpg",
			"id" : 1605,
			"position" : 9,
			"deletedStatus" : 0,
			"status" : 1
		}, {
			"image" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw00380423-1.jpg",
			"thumbnail" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw00380423-1.jpg",
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/v/r/vrrw00380423-1.jpg",
			"productId" : 231,
			"resType" : 1,
			"updateTime" : null,
			"url" : "",
			"productSpecValueId" : 0,
			"createTime" : null,
			"remoteUrl" : "https://dftv6xrgdspaa.cloudfront.net/product/image/v/r/vrrw00380423-1.jpg",
			"id" : 1606,
			"position" : 10,
			"deletedStatus" : 0,
			"status" : 1
		}, {
			"image" : "https://dftv6xrgdspaa.cloudfront.net/product/image/x/i/xinbaozhuang001_3_83.jpg",
			"thumbnail" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/x/i/xinbaozhuang001_3_83.jpg",
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/x/i/xinbaozhuang001_3_83.jpg",
			"productId" : 231,
			"resType" : 1,
			"updateTime" : null,
			"url" : "",
			"productSpecValueId" : 0,
			"createTime" : null,
			"remoteUrl" : "https://dftv6xrgdspaa.cloudfront.net/product/image/x/i/xinbaozhuang001_3_83.jpg",
			"id" : 1607,
			"position" : 11,
			"deletedStatus" : 0,
			"status" : 1
		}],
		"catalogProductEntityVideos" : [],
		"catalogProductRecommendeds" : [{
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/n/r/nrc043720161103-03.jpg",
			"productId" : 83,
			"createTime" : "2017-11-08 11:16:40",
			"name" : "X-shaped Micro Pave Round Cut Cubic Zirconia Engagement Ring",
			"spu" : "NRC0437",
			"updateTime" : "",
			"id" : 10083,
			"position" : 3,
			"deletedStatus" : 1,
			"recommendedProductId" : 10083
		}, {
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/c/d/cdr022newimage1008-03.jpg",
			"productId" : 2,
			"createTime" : "2017-11-08 11:16:50",
			"name" : "Angel Wing Sterling Silver Engagement Ring with Heart Cut Lab-created Diamonds",
			"spu" : "CDR022",
			"updateTime" : "",
			"id" : 10002,
			"position" : 3,
			"deletedStatus" : 1,
			"recommendedProductId" : 10002
		}, {
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/n/r/nrc0480-5-0725.jpg",
			"productId" : 117,
			"createTime" : "2017-11-08 11:17:36",
			"name" : "Four Leaf Clover Inspired Designer Sterling Silver Promise Ring",
			"spu" : "NRC0480",
			"updateTime" : "",
			"id" : 10117,
			"position" : 3,
			"deletedStatus" : 1,
			"recommendedProductId" : 10117
		}, {
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/n/r/nrc0465-5-0428.jpg",
			"productId" : 105,
			"createTime" : "2017-11-08 11:17:36",
			"name" : "The Chain Four Skulls Punk Style Ring For Women for Halloween Gift",
			"spu" : "NRC0465",
			"updateTime" : "",
			"id" : 10105,
			"position" : 3,
			"deletedStatus" : 1,
			"recommendedProductId" : 10105
		}, {
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/n/r/nrc0466-4-0428_1.jpg",
			"productId" : 106,
			"createTime" : "2017-11-08 11:17:36",
			"name" : "Owl Inspired Trilogy Ring In White Gold Plated Sterling Silver For Women",
			"spu" : "NRC0466",
			"updateTime" : "",
			"id" : 10106,
			"position" : 3,
			"deletedStatus" : 1,
			"recommendedProductId" : 10106
		}, {
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/n/r/nrc0450-420170309.jpg",
			"productId" : 92,
			"createTime" : "2017-11-08 11:17:55",
			"name" : "Round Cut Daisy Promise Ring In Sterling Silver For Women",
			"spu" : "NRC0450",
			"updateTime" : "",
			"id" : 10092,
			"position" : 3,
			"deletedStatus" : 1,
			"recommendedProductId" : 10092
		}, {
			"smallImage" : "https://dftv6xrgdspaa.cloudfront.net/product/smallimage/n/r/nrc0000-2-0925.jpg",
			"productId" : 61,
			"createTime" : "2017-11-08 11:18:10",
			"name" : "Heart Cut 925 Sterling Silver White Gold Plated Cubic Zirconia Ring",
			"spu" : "NRC0000",
			"updateTime" : "",
			"id" : 10061,
			"position" : 3,
			"deletedStatus" : 1,
			"recommendedProductId" : 10061
		}]
	}
}
